### ISSUE TITLE
Add new "DEA datasets" notebook for Sentinel-2 Collection 3 data

### ISSUE THREAD

**Issue by robbibt** [GeoscienceAustralia/dea-notebooks#981] opened 2022-11-15 05:10 UTC
The DEA datasets folder of DEA Notebooks includes standardised notebooks that introduce each of our products and how to get started with them using the Datacube:
https://docs.dea.ga.gov.au/notebooks/DEA_datasets/README.html

These notebooks include a set of standard sections to make it easy for users to follow along and compare between products:

**1. Background:** Taken directly from CMI
**2. Description:** A brief summary of what is included in the notebook
**3. Getting started:** Some setup steps like loading Python packages and connecting to the datacube
**4. Available products and measurements:** Inspecting the data using `dc.list_products()` and `dc.list_mesurements()`
**5. Loading data:** Simplest/minimal example of loading the data and plotting it
**6. Example application:** A small "demo" using the product, e.g. designed to show how it could be loaded and manipulated in a realistic workflow (e.g. loading the data, applying a cloud mask etc), and highlighting any common "gotchas" or things users should be aware of when using it

We should create a similar notebook for Sentinel-2 Collection 3, showing users what products and bands are available, how to load and plot the data, and perhaps how to use some of its special features (e.g. `s2cloudless`, filtering by GQA metadata, maturity etc). 

You can see some nice examples of DEA dataset notebooks here; these could be a nice template for this work:

- https://docs.dea.ga.gov.au/notebooks/DEA_datasets/DEA_Water_Observations.html
- https://docs.dea.ga.gov.au/notebooks/DEA_datasets/DEA_Fractional_Cover.html

There is [an ancient Sentinel-2 notebook here](https://docs.dea.ga.gov.au/notebooks/DEA_datasets/Sentinel_2.html) that may be useful for this, but it doesn't match the formatting of the other DEA dataset notebooks... we might be better off starting from scratch rather than adapting this

**Comment by geoscience-aman** [comment] 2023-01-16 05:04
Duplicate of PR #983

**Closed as not planned by geoscience-aman** 2023-01-16 05:04 UTC
Labels: Sentinel-2 Collection 3
